{% set version = "1.0.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-chemospecutils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ChemoSpecUtils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ChemoSpecUtils/ChemoSpecUtils_{{ version }}.tar.gz
  sha256: 494d92eab7c70e74fe75c3c0b813c4fd3b345cac1391b3efb034df208cebc2e8

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-ggrepel
    - r-magrittr
    - r-plotly
    - r-plyr
  run:
    - r-base
    - r-ggplot2
    - r-ggrepel
    - r-magrittr
    - r-plotly
    - r-plyr

test:
  commands:
    - $R -e "library('ChemoSpecUtils')"           # [not win]
    - "\"%R%\" -e \"library('ChemoSpecUtils')\""  # [win]

about:
  home: https://github.com/bryanhanson/ChemoSpecUtils
  license: GPL-3.0-only
  summary: Functions supporting the common needs of packages 'ChemoSpec' and 'ChemoSpec2D'.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ChemoSpecUtils
# Type: Package
# Title: Functions Supporting Packages ChemoSpec and ChemoSpec2D
# Version: 0.2.204
# Date: 2018-12-19
# Authors@R: c( person("Bryan A.", "Hanson", role = c("aut", "cre"), email = "hanson@depauw.edu", comment = "ORCID 0000-0003-3536-8246"))
# Description: Functions supporting the common needs of packages 'ChemoSpec' and 'ChemoSpec2D'.
# License: GPL-3
# Depends: R (>= 3.1)
# Suggests: ChemoSpec (>= 5.0), ChemoSpec2D, testthat
# Imports: plyr, robustbase, RColorBrewer, amap
# URL: https://github.com/bryanhanson/ChemoSpecUtils
# BugReports: https://github.com/bryanhanson/ChemoSpecUtils/issues
# ByteCompile: TRUE
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2018-12-19 15:08:31 UTC; bryanhanson
# Author: Bryan A. Hanson [aut, cre] (ORCID 0000-0003-3536-8246)
# Maintainer: Bryan A. Hanson <hanson@depauw.edu>
# Repository: CRAN
# Date/Publication: 2018-12-19 16:10:03 UTC
