{% set version = "0.3.39" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-chemospecutils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ChemoSpecUtils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ChemoSpecUtils/ChemoSpecUtils_{{ version }}.tar.gz
  sha256: fca8b73e35474f946325c002fd11b4cc33eb88f1f1e0c48b3543b86263aca7ed

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-amap
    - r-plyr
    - r-robustbase
  run:
    - r-base
    - r-rcolorbrewer
    - r-amap
    - r-plyr
    - r-robustbase

test:
  commands:
    - $R -e "library('ChemoSpecUtils')"           # [not win]
    - "\"%R%\" -e \"library('ChemoSpecUtils')\""  # [win]

about:
  home: https://github.com/bryanhanson/ChemoSpecUtils
  license: GPL-3
  summary: Functions supporting the common needs of packages 'ChemoSpec' and 'ChemoSpec2D'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ChemoSpecUtils
# Type: Package
# Title: Functions Supporting Packages ChemoSpec and ChemoSpec2D
# Version: 0.2.204
# Date: 2018-12-19
# Authors@R: c( person("Bryan A.", "Hanson", role = c("aut", "cre"), email = "hanson@depauw.edu", comment = "ORCID 0000-0003-3536-8246"))
# Description: Functions supporting the common needs of packages 'ChemoSpec' and 'ChemoSpec2D'.
# License: GPL-3
# Depends: R (>= 3.1)
# Suggests: ChemoSpec (>= 5.0), ChemoSpec2D, testthat
# Imports: plyr, robustbase, RColorBrewer, amap
# URL: https://github.com/bryanhanson/ChemoSpecUtils
# BugReports: https://github.com/bryanhanson/ChemoSpecUtils/issues
# ByteCompile: TRUE
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2018-12-19 15:08:31 UTC; bryanhanson
# Author: Bryan A. Hanson [aut, cre] (ORCID 0000-0003-3536-8246)
# Maintainer: Bryan A. Hanson <hanson@depauw.edu>
# Repository: CRAN
# Date/Publication: 2018-12-19 16:10:03 UTC
