{% set version = "0.2.204" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-chemospecutils
  version: {{ version|replace("-", "_") }}

source:
  fn: ChemoSpecUtils_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ChemoSpecUtils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ChemoSpecUtils/ChemoSpecUtils_{{ version }}.tar.gz
  sha256: a05f3d90a1fea7e301cce367ec8e19aafe05c2f0235a45a465d853f147848348

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-plyr
    - r-robustbase
  run:
    - r-base
    - r-rcolorbrewer
    - r-plyr
    - r-robustbase

test:
  commands:
    - $R -e "library('ChemoSpecUtils')"           # [not win]
    - "\"%R%\" -e \"library('ChemoSpecUtils')\""  # [win]

about:
  home: https://github.com/bryanhanson/ChemoSpecUtils
  license: GPL-3
  summary: Functions supporting the common needs of packages 'ChemoSpec' and 'ChemoSpec2D'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
