appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: dGsFTwH/1K1S0S8eYkO6UxlDe1VMPBs1J54G5/C32eMS/CgVEN1SgBVtu5U6wJBbpxAcKOAaq/BZDizqxqjrmzsL0j6LrbAbySpm8LTSzP7zX/G75q+UWzb+tSbna1/ezwAKIGXbcZMprh+vNy+ZX/KU6O53GSPidJ89bEdDvkJmvgFvbXrJHGK8LuLIOchmUd99RXg/aOnS28yMu2OJDZVXK+cz6G+lfbJlAVwJP8Cv1XvEsxyCxBBjTDgMuWXWhGj1EjEazaRa/gVfuuKGCaDIHeaBvYXmvoKvjeXDjONRXPyM7rW7i5RAT5FpDYviXt+ppacu9oJQHY9y7TR1GVqfPd2KbG4CFqcCSp7El4z7J5Dw4cetw3hdWdUKhGqyP6Xpwi5EHtztRHL2Xi4PmpkViE9s0X3FSZsdxqgcJIOflK5T1IWclDeYPoc4BUUUpT2//QRKkw2bs+7AES2R3IIFsuepWi0JckDVTgDOzjHyD0dYH4bRoqH2/jSqox9sz3t04cW01LqW5WFA5Q2tVZ4rzyP4MAmem+ct6zj8lhcH8IKzmAiSKgLZDf3Dm9c43ZqfUvAhAelcMmrJ3MQNvwDAXtdmi5n2UHViwns6/FdKvXhp3TkoBK+UvI0HpGFjuIKIRFe5wXwdihXYe0dGt4z0JsgE3ssr90mBX/EX6GY=}
